'use client';
import { useMemo, useState } from 'react';
import { Activity, CalendarDays, ChevronRight, Clock3, Database, FileSearch, FolderOpen, LayoutDashboard, RefreshCw, Search, ShieldCheck, Sparkles } from 'lucide-react';
const records=[
 {boe:'BOE-2026-009812',date:'29 Sep 2026',type:'BOE',location:'DXB',folder:'September / Import Operation',status:'Active'},
 {boe:'305-7781',date:'29 Sep 2026',type:'305',location:'DXB',folder:'September / Import Operation',status:'Active'},
 {boe:'DXB-48192',date:'28 Sep 2026',type:'DXB',location:'DXB',folder:'September / Active',status:'Active'},
 {boe:'BOE-2026-009731',date:'28 Sep 2026',type:'BOE',location:'DXB',folder:'September / Import Operation',status:'Active'},
 {boe:'305-7610',date:'27 Sep 2026',type:'305',location:'DXB',folder:'September / Active',status:'Active'}
];
export default function Home(){
 const [q,setQ]=useState(''); const [scanning,setScanning]=useState(false);
 const filtered=useMemo(()=>records.filter(r=>Object.values(r).join(' ').toLowerCase().includes(q.toLowerCase())),[q]);
 const scan=()=>{setScanning(true);setTimeout(()=>setScanning(false),1200)};
 return <div className="shell"><header className="topbar"><div className="brand"><div className="brandmark"><Sparkles size={18}/></div><span>BOE Intelligence</span></div><div className="top-actions"><span className="pill"><span className="dot"/>Scanner online</span><span className="pill hide-mobile">29 Sep 2026</span></div></header>
 <div className="layout"><aside className="sidebar"><div className="navgroup">Workspace</div><a className="navitem active"><LayoutDashboard size={17}/>Overview</a><a className="navitem"><FileSearch size={17}/>BOE Search</a><a className="navitem"><CalendarDays size={17}/>Daily Activity</a><a className="navitem"><FolderOpen size={17}/>Folder Explorer</a><div className="navgroup">System</div><a className="navitem"><Activity size={17}/>Scanner Center</a><a className="navitem"><Database size={17}/>Data Health</a><a className="navitem"><ShieldCheck size={17}/>Audit Trail</a></aside>
 <main className="main"><section className="hero"><div><div className="eyebrow">Operations intelligence · 2026</div><h1 className="title">A calmer way to<br/>find every BOE.</h1><p className="subtitle">A premium web control center for the existing 2026 BOE scanner — preserving its folder discovery, CLOSED rules, change history and matching logic while replacing the spreadsheet experience.</p></div><button className="button" onClick={scan}><RefreshCw size={15} style={{verticalAlign:'-2px',marginRight:7}}/>{scanning?'Scanning…':'Scan now'}</button></section>
 <section className="cards"><div className="card"><span className="muted">Tracked records</span><div className="metric">2,713</div><span className="muted">Preserved from current system</span></div><div className="card"><span className="muted">New today</span><div className="metric">18</div><span className="muted">Since 00:00</span></div><div className="card"><span className="muted">Matches</span><div className="metric">4</div><span className="muted">BOE · 305 · DXB</span></div><div className="card"><span className="muted">Last scan</span><div className="metric">09:10</div><span className="muted">Next cycle · 09:15</span></div></section>
 <section className="section"><div className="panel"><div className="panelhead"><div><div className="paneltitle">Search intelligence</div><div className="muted">Search across the indexed file metadata</div></div><Search size={18} color="#999"/></div><div className="search"><Search size={17} color="#999"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search BOE, 305, DXB, date, folder…"/></div><div className="filters"><span className="filter">All records</span><span className="filter">September 2026</span><span className="filter">Active only</span><span className="filter">Exact folder links</span></div><div style={{overflowX:'auto',marginTop:18}}><table className="table"><thead><tr><th>Reference</th><th>Date</th><th>Match</th><th>Folder</th><th>Status</th></tr></thead><tbody>{filtered.map(r=><tr key={r.boe}><td><b>{r.boe}</b></td><td>{r.date}</td><td>{r.type}</td><td>{r.folder}</td><td><span className="badge">{r.status}</span></td></tr>)}</tbody></table></div></div>
 <div className="panel"><div className="panelhead"><div><div className="paneltitle">Scanner center</div><div className="muted">Local network agent status</div></div><Activity size={18}/></div><div className="scan"><div><div className="scanstatus">{scanning?'Scanning source tree':'Ready'}</div><div className="muted">Z:\PROJECT_LOGISTICS\Car Project\Import operation\2026</div></div><Clock3 size={22} color="#777"/></div><div className="scan"><div><div className="scanstatus">Every 5 minutes</div><div className="muted">Windows scheduled scanner</div></div><ChevronRight size={18}/></div><div className="scan"><div><div className="scanstatus">CLOSED-aware</div><div className="muted">Inactive subtrees excluded</div></div><ShieldCheck size={18}/></div></div></section>
 <section className="section single"><div className="panel"><div className="panelhead"><div><div className="paneltitle">Live activity</div><div className="muted">Latest scanner events</div></div><span className="pill">Today</span></div><div className="timeline"><div className="event"><span className="eventdot"/><div><b>Scan completed</b><div className="muted">September active folders checked successfully</div></div><span className="eventtime">09:10</span></div><div className="event"><span className="eventdot"/><div><b>4 matches detected</b><div className="muted">BOE / 305 / DXB filename matching</div></div><span className="eventtime">09:10</span></div><div className="event"><span className="eventdot"/><div><b>18 new records today</b><div className="muted">Existing history preserved; no source changes</div></div><span className="eventtime">09:09</span></div></div></div></section>
 <div className="footer">BOE Intelligence · Online interface prototype · Source files remain read-only</div></main></div></div>
}